---
schema:
  procedures: {}
  tables:
    role:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        id:
          data_type: int
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 2
          size:
            - 80
      indices: []
      name: role
      options: []
      order: 1
    session:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
      fields:
        expires:
          data_type: int
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: expires
          order: 3
          size:
            - 0
        id:
          data_type: char
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 72
        session_data:
          data_type: text
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: session_data
          order: 2
          size:
            - 0
      indices: []
      name: session
      options: []
      order: 2
    siteuser:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
            - username
          match_type: ''
          name: siteuser_email_username
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 2
          size:
            - 50
        first_name:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: first_name
          order: 5
          size:
            - 50
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        last_name:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: last_name
          order: 6
          size:
            - 50
        password:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 4
          size:
            - 255
        username:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: username
          order: 3
          size:
            - 50
      indices: []
      name: siteuser
      options: []
      order: 3
    siteuser_role:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - siteuser
            - role
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - role
          match_type: ''
          name: siteuser_role_fk_role
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: role
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - siteuser
          match_type: ''
          name: siteuser_role_fk_siteuser
          on_delete: CASCADE
          on_update: CASCADE
          options: []
          reference_fields:
            - id
          reference_table: siteuser
          type: FOREIGN KEY
      fields:
        role:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: role
          order: 2
          size:
            - 0
        siteuser:
          data_type: int
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: siteuser
          order: 1
          size:
            - 0
      indices:
        - fields:
            - role
          name: siteuser_role_idx_role
          options: []
          type: NORMAL
        - fields:
            - siteuser
          name: siteuser_role_idx_siteuser
          options: []
          type: NORMAL
      name: siteuser_role
      options: []
      order: 4
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Role
      - Session
      - Siteuser
      - SiteuserRole
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 0.11018
